
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('song').del()
    .then(function () {
      // Inserts seed entries
      return knex('song').insert([
        {artist_id: 1, title: '8 Feet of Chain', album: 'Arnos Farm', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/8+Feet+of+Chain.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/arnosfarmcover.jpg'},
        {artist_id: 1, title: 'Along the Road', album: 'Arnos Farm', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/Along+the+Road.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/arnosfarmcover.jpg'},
        {artist_id: 1, title: 'Gaslight Waltz', album: 'Arnos Farm', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/Gaslight+Waltz.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/arnosfarmcover.jpg'},
        {artist_id: 1, title: 'Ghosts of Jerome', album: 'Arnos Farm', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/Ghosts+of+Jerome.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/arnosfarm/arnosfarmcover.jpg'},
        {artist_id: 2, title: 'Fortnight', album: 'Move', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/Fortnight.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallmove.jpg'},
        {artist_id: 2, title: 'Culmination', album: 'Move', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/Culmination.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallmove.jpg'},
        {artist_id: 2, title: 'Bright Side Dark Side', album: 'Bright Side Dark Side', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/Bright+Side++Dark+Side.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallbrightside.jpg'},
        {artist_id: 2, title: 'To Become', album: 'Move', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/To+Become.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallmove.jpg'},
        {artist_id: 2, title: 'What You Got', album: 'Bright Side Dark Side', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/What+You+Got.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallbrightside.jpg'},
        {artist_id: 2, title: 'Comes and Goes', album: 'Bright Side Dark Side', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/Comes+and+Goes.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/benhall/benhallbrightside.jpg'},
        {artist_id: 3, title: 'Going Back', album: 'Golden Oppurtunity', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/Going+Back.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/preservegoldenopp.jpg'},
        {artist_id: 3, title: 'Drink Up', album: 'Golden Oppurtunity', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/Drink+Up.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/preservegoldenopp.jpg'},
        {artist_id: 3, title: 'Like a Man', album: 'Golden Oppurtunity', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/Like+a+Man.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/preservegoldenopp.jpg'},
        {artist_id: 3, title: 'Raising Cane', album: 'Golden Oppurtunity', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/Raising+Cane.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/thepreserve/preservegoldenopp.jpg'},
        {artist_id: 4, title: 'Simple Times', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Simple+Times.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Time', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Time.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Nightmare', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Nightmare.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Hollywood', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Fadeaway.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Fadeaway', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Hollywood.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Fadeaway', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Fortunate+Son.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Fadeaway', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Push.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 4, title: 'Fadeaway', album: 'Hollywood', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/Crack.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/colorofchaos/hollywood-color-of-chaos.jpg'},
        {artist_id: 5, title: 'Fear', album: 'Shedding Skin', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/Fear.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/interfatesheddingskin.jpg'},
        {artist_id: 5, title: '5 Letter Name', album: 'Shedding Skin', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/5+Letter+Name.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/interfatesheddingskin.jpg'},
        {artist_id: 5, title: 'Change My Mind', album: 'Shedding Skin', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/Change+My+Mind.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/interfatesheddingskin.jpg'},
        {artist_id: 5, title: 'Curtain Call', album: 'Shedding Skin', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/Curtain+Call.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/interfate/interfatesheddingskin.jpg'},
        {artist_id: 6, title: 'Come Along for the Ride', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Come+Along+for+the+Ride.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Online', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Online.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Kar Krash', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Kar+Krash.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Saints', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Saints.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'MFC', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/MFC.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Cut', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Cut.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Mary Goes Around', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Mary+Goes+Around.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Inhaler', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Inhaler.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Leave It to Me', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Leave+It+to+Me.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 6, title: 'Olde White Ghost', album: 'Conditional Love Casino', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/Olde+White+Ghost.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/jesusponies/jesusponiesconditional.jpg'},
        {artist_id: 7, title: 'Pretty Pollyanne-Say Old Man Can I Have Your Daughter?', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Pretty+Pollyanne+-+Say+Old+Man+Can+I+Have+Your+Daughter.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Cage', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Cage.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Live Forever', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Live+Forever.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Collision', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Collision.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Funk in the Trunk', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Funk+in+the+Trunk.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Mad World', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Mad+World.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},
        {artist_id: 7, title: 'Sugar & Stone', album: 'No Pardon', url: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/Sugar+and+Stone.ogg', album_art: 'https://s3-us-west-1.amazonaws.com/soundwavessongs1/nopardon/nopardonepcover.jpg'},

      ]);
    });
};
